'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';

import {
  flattenTraceForPlayback,
  formatMatchTimeRange,
  isTruncatedToolOutput,
  totalPlaybackDurationMs,
  type PlaybackItem,
} from '@/lib/agentTracePlayback';
import { colors, motion as motionTokens } from '@/lib/design-tokens';
import { usePanopticonState } from '@/lib/PanopticonProvider';
import type {
  AgentTrace,
  TraceHandoff,
  TraceText,
  TraceThinking,
  TraceToolCall,
  TraceToolResult,
} from '@/lib/types';

/**
 * Tab 3 — Live Agent Orchestration Console (PATTERN-056 / USER-CORRECTION-024).
 *
 * Loads `agent_trace.json` (generated by the offline Scouting Committee run
 * during precompute) via `fetch()` in `useEffect` — never as a Server Component
 * prop (GOTCHA-026 hydration death). Plays back the captured event sequence
 * with deterministic pacing so judges physically see the multi-agent
 * reasoning unfold: Analytics Specialist → Technical Coach → Tactical Strategist.
 *
 * The "ARCHITECTURAL PREVIEW: SWARM ACCELERATED FOR DEMO" banner discloses
 * that playback pacing is UI-only — the real reasoning happened offline.
 */
export default function OrchestrationConsoleTab() {
  const { matchData } = usePanopticonState();
  const [trace, setTrace] = useState<AgentTrace | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [cursor, setCursor] = useState(0); // index of NEXT item to reveal
  // Fast Forward: 1× is real baud-rate pacing (~25 cps); 4× divides every
  // setTimeout delay by 4 so judges can skim the long text blocks.
  const [playbackSpeed, setPlaybackSpeed] = useState<1 | 4>(1);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const matchId = matchData?.meta.match_id ?? 'utr_01_segment_a';

  // Load agent_trace.json — client-side fetch, NEVER RSC props (GOTCHA-026)
  useEffect(() => {
    let cancelled = false;
    fetch('/match_data/agent_trace.json')
      .then((r) => {
        if (!r.ok) {
          throw new Error(`agent_trace.json ${r.status}`);
        }
        return r.json() as Promise<AgentTrace>;
      })
      .then((data) => {
        if (!cancelled) setTrace(data);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setLoadError(err instanceof Error ? err.message : String(err));
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const items = useMemo<PlaybackItem[]>(
    () => (trace ? flattenTraceForPlayback(trace) : []),
    [trace],
  );
  const totalMs = useMemo(() => (trace ? totalPlaybackDurationMs(trace) : 0), [trace]);

  const revealedItems = items.slice(0, cursor);
  const finished = cursor >= items.length && items.length > 0;

  // Playback driver: advance cursor after each item's delay
  useEffect(() => {
    if (!isPlaying) return;
    if (cursor >= items.length) {
      setIsPlaying(false);
      return;
    }
    const currentItem = items[cursor];
    const prevReveal = cursor === 0 ? 0 : items[cursor - 1].revealAtMs;
    const delayMs = currentItem.revealAtMs - prevReveal;
    // Scale by playback speed — 4× means "skim real reasoning" not "skip to end".
    const scaledDelay = Math.max(1, Math.round(delayMs / playbackSpeed));

    timerRef.current = setTimeout(() => {
      setCursor((c) => c + 1);
    }, scaledDelay);

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [isPlaying, cursor, items, playbackSpeed]);

  const onPlay = useCallback(() => {
    if (cursor >= items.length) setCursor(0); // restart if finished
    setIsPlaying(true);
  }, [cursor, items.length]);
  const onPause = useCallback(() => setIsPlaying(false), []);
  const onSkipToEnd = useCallback(() => {
    setIsPlaying(false);
    setCursor(items.length);
  }, [items.length]);
  const onRestart = useCallback(() => {
    setIsPlaying(false);
    setCursor(0);
    setPlaybackSpeed(1);
  }, []);
  const onToggleSpeed = useCallback(() => {
    setPlaybackSpeed((s) => (s === 1 ? 4 : 1));
  }, []);

  if (loadError) {
    return (
      <TabChrome matchId={matchId}>
        <div
          className="mx-auto w-full max-w-[900px] rounded-xl border p-8 text-[13px]"
          style={{ background: colors.bg1, borderColor: colors.border, color: colors.anomaly }}
        >
          <p className="font-semibold">Could not load agent_trace.json</p>
          <p className="mt-2" style={{ color: colors.textSecondary }}>
            {loadError}
          </p>
          <p className="mt-3" style={{ color: colors.textMuted }}>
            Expected at <code>/match_data/agent_trace.json</code>. Re-run{' '}
            <code>python -m backend.precompute …</code> with an ANTHROPIC_API_KEY to generate it.
          </p>
        </div>
      </TabChrome>
    );
  }

  if (!trace) {
    return (
      <TabChrome matchId={matchId}>
        <div
          className="mx-auto w-full max-w-[900px] rounded-xl border p-8 text-center text-[13px]"
          style={{ background: colors.bg1, borderColor: colors.border, color: colors.textMuted }}
        >
          <span className="mono">Loading committee trace…</span>
        </div>
      </TabChrome>
    );
  }

  const progressPct = totalMs === 0 ? 0 : (revealedItems.length === 0
    ? 0
    : (revealedItems[revealedItems.length - 1].revealAtMs / totalMs) * 100);

  const matchTimecode = formatMatchTimeRange(trace.match_time_range_ms ?? null);

  return (
    <TabChrome matchId={matchId}>
      <div className="mx-auto w-full max-w-[1200px] flex-1 overflow-y-auto">
        <PreviewBanner />
        {matchTimecode && <MatchTimecodeAnchor timecode={matchTimecode} />}
        <CommitteeGoal goal={trace.committee_goal} />
        <TransportBar
          isPlaying={isPlaying}
          finished={finished}
          cursor={cursor}
          total={items.length}
          progressPct={progressPct}
          playbackSpeed={playbackSpeed}
          onPlay={onPlay}
          onPause={onPause}
          onSkipToEnd={onSkipToEnd}
          onRestart={onRestart}
          onToggleSpeed={onToggleSpeed}
        />

        <section className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
          {trace.steps.map((step, i) => (
            <AgentColumn
              key={`${step.agent_name}-${i}`}
              step={step}
              stepIndex={i}
              revealedItems={revealedItems}
            />
          ))}
        </section>

        {finished && (
          <motion.section
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={motionTokens.springStandard}
            className="mx-auto mt-8 max-w-[900px] rounded-xl border p-8"
            style={{ background: colors.bg1, borderColor: colors.border }}
          >
            <header className="mb-4 flex items-center gap-2">
              <span
                className="mono text-[10px] uppercase tracking-[0.18em]"
                style={{ color: colors.opusThinking }}
              >
                Final Tactical Brief
              </span>
            </header>
            <div
              className="scouting-markdown prose prose-invert prose-sm max-w-none"
              style={{ color: colors.textPrimary }}
            >
              <ReactMarkdown>{trace.final_report_markdown}</ReactMarkdown>
            </div>
          </motion.section>
        )}
      </div>
      <ConsoleStyles />
    </TabChrome>
  );
}

// ──────────────────────────── Sub-components ────────────────────────────

function TabChrome({ matchId, children }: { matchId: string; children: React.ReactNode }) {
  return (
    <div
      className="flex min-h-[calc(100vh-72px)] flex-col gap-6 p-6 lg:p-10"
      style={{ background: colors.bg0 }}
    >
      <header className="mx-auto w-full max-w-[1200px]">
        <div className="flex items-center gap-4">
          <h2
            className="text-[22px] font-bold tracking-tight"
            style={{ color: colors.textPrimary }}
          >
            Scouting Committee
          </h2>
          <span
            className="mono text-[10px] uppercase tracking-[0.16em]"
            style={{ color: colors.textMuted }}
          >
            match {matchId} · 3 agents · claude-opus-4-7
          </span>
        </div>
        <p
          className="mt-1 max-w-[70ch] text-[13px]"
          style={{ color: colors.textSecondary }}
        >
          A three-agent Opus 4.7 swarm analyzes Player A&apos;s biomechanical
          telemetry. Analytics identifies anomalies; Technical Coach grounds
          them in biomech literature; Tactical Strategist synthesizes the
          exploit.
        </p>
      </header>
      {children}
    </div>
  );
}

function PreviewBanner() {
  return (
    <div
      className="mx-auto mb-5 flex max-w-[1200px] items-center gap-2 rounded border px-3 py-2 text-[11px]"
      style={{
        background: `${colors.opusThinking}10`,
        borderColor: `${colors.opusThinking}55`,
        color: colors.opusThinking,
      }}
    >
      <span className="mono uppercase tracking-[0.18em]">Architectural Preview</span>
      <span style={{ color: colors.textMuted }}>·</span>
      <span style={{ color: colors.textSecondary }}>
        Swarm accelerated for demo — the real 45-60s reasoning loop runs offline
        during precompute; the UI replays the captured trace with timed pacing.
      </span>
    </div>
  );
}

function MatchTimecodeAnchor({ timecode }: { timecode: string }) {
  // Phase 4 UX sync: surface WHICH match-time window the swarm analyzed so
  // judges can map the trace playback to the video timecode they're watching.
  // Positioned BETWEEN the Architectural Preview banner and the Committee Goal
  // so it's immediately visible before any reasoning content scrolls in.
  return (
    <div
      className="mx-auto mt-2 flex max-w-[1200px] items-center gap-2 text-[11px]"
      style={{ color: colors.textMuted }}
    >
      <span
        className="mono rounded px-2 py-1 uppercase tracking-[0.16em]"
        style={{
          background: `${colors.playerA}10`,
          color: colors.playerA,
          fontSize: 10,
        }}
      >
        Match timecode
      </span>
      <span className="mono" style={{ color: colors.textPrimary, fontSize: 12 }}>
        {timecode}
      </span>
      <span style={{ color: colors.textMuted }}>
        — the window of the match this committee is analyzing
      </span>
    </div>
  );
}

function CommitteeGoal({ goal }: { goal: string }) {
  return (
    <div
      className="mx-auto mt-4 flex max-w-[1200px] items-start gap-3 rounded border px-4 py-3"
      style={{ background: colors.bg1, borderColor: colors.border }}
    >
      <span
        className="mono text-[10px] uppercase tracking-[0.16em]"
        style={{ color: colors.textMuted, paddingTop: 2 }}
      >
        Goal
      </span>
      <p className="flex-1 text-[13px]" style={{ color: colors.textPrimary }}>
        {goal}
      </p>
    </div>
  );
}

function TransportBar({
  isPlaying,
  finished,
  cursor,
  total,
  progressPct,
  playbackSpeed,
  onPlay,
  onPause,
  onSkipToEnd,
  onRestart,
  onToggleSpeed,
}: {
  isPlaying: boolean;
  finished: boolean;
  cursor: number;
  total: number;
  progressPct: number;
  playbackSpeed: 1 | 4;
  onPlay: () => void;
  onPause: () => void;
  onSkipToEnd: () => void;
  onRestart: () => void;
  onToggleSpeed: () => void;
}) {
  return (
    <div className="mx-auto mt-4 flex max-w-[1200px] items-center gap-3">
      {!isPlaying && !finished && (
        <TransportButton onClick={onPlay} accent>
          {cursor === 0 ? '▶  Play Committee' : '▶  Resume'}
        </TransportButton>
      )}
      {isPlaying && (
        <TransportButton onClick={onPause}>⏸  Pause</TransportButton>
      )}
      {finished && (
        <TransportButton onClick={onRestart}>↻  Replay</TransportButton>
      )}
      {!finished && (
        <TransportButton
          onClick={onToggleSpeed}
          active={playbackSpeed === 4}
          title="Accelerate playback — keeps the full trace visible but skims the long text blocks"
        >
          {playbackSpeed === 4 ? '▶  1× Speed' : '»  4× Speed'}
        </TransportButton>
      )}
      {!finished && (
        <TransportButton onClick={onSkipToEnd}>⏭  Skip to brief</TransportButton>
      )}
      <div className="flex-1">
        <div
          className="h-1 rounded-full"
          style={{ background: `${colors.border}` }}
        >
          <div
            className="h-1 rounded-full transition-all duration-200"
            style={{ width: `${progressPct}%`, background: colors.opusThinking }}
          />
        </div>
      </div>
      <span
        className="mono text-[10px] uppercase tracking-[0.16em]"
        style={{ color: colors.textMuted }}
      >
        {cursor} / {total} events{playbackSpeed === 4 ? ' · 4×' : ''}
      </span>
    </div>
  );
}

function TransportButton({
  onClick,
  accent,
  active,
  title,
  children,
}: {
  onClick: () => void;
  accent?: boolean;
  active?: boolean;
  title?: string;
  children: React.ReactNode;
}) {
  // Three visual states:
  //  - accent: primary action (Play)
  //  - active: toggle ON (Fast Forward currently engaged)
  //  - default: secondary action
  const background = accent
    ? colors.opusThinking
    : active
      ? `${colors.opusThinking}22`
      : 'transparent';
  const borderColor = accent || active ? colors.opusThinking : colors.border;
  const color = accent
    ? '#FFFFFF'
    : active
      ? colors.opusThinking
      : colors.textSecondary;
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      className="mono rounded border px-3 py-1.5 text-[11px] uppercase tracking-[0.14em] transition-colors"
      style={{ background, borderColor, color }}
    >
      {children}
    </button>
  );
}

function AgentColumn({
  step,
  stepIndex,
  revealedItems,
}: {
  step: (AgentTrace['steps'])[number];
  stepIndex: number;
  revealedItems: ReadonlyArray<PlaybackItem>;
}) {
  const mine = revealedItems.filter((it) => it.stepIndex === stepIndex);
  const isActive = mine.length > 0 && mine.length < step.events.length;
  const isComplete = mine.length >= step.events.length && step.events.length > 0;
  const statusLabel = isComplete ? 'complete' : isActive ? 'active' : 'pending';
  const statusColor = isComplete
    ? colors.playerA
    : isActive
      ? colors.opusThinking
      : colors.textMuted;

  return (
    <div
      className="flex flex-col rounded-xl border p-4"
      style={{
        background: colors.bg1,
        borderColor: isActive ? colors.opusThinking : colors.border,
        boxShadow: isActive ? `0 0 24px ${colors.opusThinking}33` : 'none',
        transition: 'all 250ms ease',
        minHeight: 340,
      }}
    >
      <header className="mb-3 flex items-center justify-between">
        <div className="flex flex-col">
          <span
            className="text-[13px] font-semibold"
            style={{ color: colors.textPrimary }}
          >
            {step.agent_name}
          </span>
          <span
            className="mono text-[10px] uppercase tracking-[0.14em]"
            style={{ color: colors.textMuted }}
          >
            {step.agent_role}
          </span>
        </div>
        <span
          className="mono text-[9px] uppercase tracking-[0.18em]"
          style={{ color: statusColor }}
        >
          {statusLabel}
        </span>
      </header>

      <div className="flex flex-1 flex-col gap-2">
        <AnimatePresence initial={false}>
          {mine.map((it) => (
            <EventPill key={`${stepIndex}-${it.event.t_ms}-${it.event.kind}`} item={it} />
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
}

function EventPill({ item }: { item: PlaybackItem }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
    >
      {renderEvent(item.event)}
    </motion.div>
  );
}

function renderEvent(event: PlaybackItem['event']) {
  switch (event.kind) {
    case 'thinking':
      return <ThinkingEvent event={event} />;
    case 'tool_call':
      return <ToolCallEvent event={event} />;
    case 'tool_result':
      return <ToolResultEvent event={event} />;
    case 'text':
      return <TextEvent event={event} />;
    case 'handoff':
      return <HandoffEvent event={event} />;
  }
}

function ThinkingEvent({ event }: { event: TraceThinking }) {
  return (
    <div
      className="rounded border-l-2 px-3 py-2 italic"
      style={{
        background: `${colors.opusThinking}08`,
        borderColor: colors.opusThinking,
        color: colors.textSecondary,
        fontSize: 12,
        lineHeight: 1.5,
      }}
    >
      <span
        className="mono mb-1 block text-[9px] uppercase tracking-[0.16em]"
        style={{ color: colors.opusThinking, fontStyle: 'normal' }}
      >
        Thinking
      </span>
      {event.content}
    </div>
  );
}

/** Provenance chip rendered on tool_call/tool_result events whose backend
 * implementation reads local authored JSON rather than a live Anthropic tool
 * (G9 / A9). Informs judges that `query_video_context_mcp` is a stub for
 * demo — honest disclosure that the Tab 3 narration handoff is architecturally
 * real but the video-MCP endpoint is a placeholder. Non-alarming neutral
 * styling — it's a capability marker, not an error indicator. */
function ProvenanceChip({ tag }: { tag: 'stubbed_mcp' | 'live_anthropic' }) {
  if (tag !== 'stubbed_mcp') return null;
  return (
    <span
      className="mono rounded px-1.5 py-0.5"
      style={{
        background: `${colors.opusThinking}22`,
        color: colors.opusThinking,
        fontSize: 8,
        letterSpacing: '0.14em',
      }}
      title="This tool reads local authored JSON for the hackathon demo. The LLM invoked it as a real tool — the SCHEMA and REASONING are production-grade; only the implementation is stubbed. V2 routes this call to a live Video MCP server."
    >
      STUB · Video Context API
    </span>
  );
}

function ToolCallEvent({ event }: { event: TraceToolCall }) {
  const provenance = event.provenance ?? 'live_anthropic';
  return (
    <div
      className="rounded border px-3 py-2"
      style={{ background: colors.bg2, borderColor: colors.border, fontSize: 12 }}
    >
      <span
        className="mono mb-1 flex items-center gap-2 text-[9px] uppercase tracking-[0.16em]"
        style={{ color: colors.textMuted }}
      >
        <span>Tool call · {event.tool_name}</span>
        <ProvenanceChip tag={provenance} />
      </span>
      <code
        className="mono block overflow-x-auto whitespace-pre-wrap break-words"
        style={{ color: colors.textPrimary, fontSize: 11 }}
      >
        {event.input_json}
      </code>
    </div>
  );
}

function ToolResultEvent({ event }: { event: TraceToolResult }) {
  // GOTCHA-030: event.output_json may carry the backend truncation sentinel
  // " ... [Array truncated for UI playback]" which makes it INVALID JSON.
  // NEVER call JSON.parse() on this value directly — use safeParseOutputJson
  // from @/lib/agentTracePlayback when a parsed form is required. Here we
  // only render as a raw string, which is safe.
  const isTruncated = isTruncatedToolOutput(event.output_json);
  const provenance = event.provenance ?? 'live_anthropic';
  const visibleSlice = event.output_json.length > 500
    ? event.output_json.slice(0, 500) + '…'
    : event.output_json;
  return (
    <div
      className="rounded border px-3 py-2"
      style={{
        background: event.is_error ? `${colors.anomaly}12` : `${colors.playerA}08`,
        borderColor: event.is_error ? colors.anomaly : colors.border,
        fontSize: 12,
      }}
    >
      <span
        className="mono mb-1 flex items-center gap-2 text-[9px] uppercase tracking-[0.16em]"
        style={{ color: event.is_error ? colors.anomaly : colors.playerA }}
      >
        <span>{event.is_error ? 'Tool error' : 'Tool result'} · {event.tool_name}</span>
        <ProvenanceChip tag={provenance} />
        {isTruncated && (
          <span
            className="rounded px-1.5 py-0.5"
            style={{
              background: `${colors.textMuted}22`,
              color: colors.textMuted,
              fontSize: 8,
              letterSpacing: '0.14em',
            }}
            title="Backend trimmed the full payload for UI safety (GOTCHA-027). The LLM saw the complete result during execution."
          >
            Truncated
          </span>
        )}
      </span>
      <code
        className="mono block overflow-x-auto whitespace-pre-wrap break-words"
        style={{ color: colors.textSecondary, fontSize: 11 }}
      >
        {visibleSlice}
      </code>
    </div>
  );
}

function TextEvent({ event }: { event: TraceText }) {
  return (
    <div
      className="rounded px-3 py-2"
      style={{
        background: colors.bg2,
        color: colors.textPrimary,
        fontSize: 13,
        lineHeight: 1.5,
      }}
    >
      {event.content}
    </div>
  );
}

function HandoffEvent({ event }: { event: TraceHandoff }) {
  return (
    <div
      className="mt-1 flex items-start gap-2 rounded border-l-2 px-3 py-2"
      style={{
        borderColor: colors.playerA,
        background: `${colors.playerA}08`,
        fontSize: 11,
      }}
    >
      <span style={{ color: colors.playerA }}>↳</span>
      <div className="flex-1">
        <span
          className="mono block text-[9px] uppercase tracking-[0.16em]"
          style={{ color: colors.playerA }}
        >
          Handoff → {event.to_agent}
        </span>
        <p className="mt-1" style={{ color: colors.textSecondary }}>
          {event.payload_summary}
        </p>
      </div>
    </div>
  );
}

function ConsoleStyles() {
  return (
    <style>{`
      .scouting-markdown h1 {
        font-size: 1.5rem;
        font-weight: 800;
        color: ${colors.textPrimary};
        margin: 0 0 0.5em 0;
      }
      .scouting-markdown h2 {
        font-size: 1.15rem;
        font-weight: 700;
        color: ${colors.textPrimary};
        margin: 1.4em 0 0.35em 0;
        padding-bottom: 0.3em;
        border-bottom: 1px solid ${colors.border};
      }
      .scouting-markdown h3 {
        font-size: 0.95rem;
        font-weight: 600;
        color: ${colors.textPrimary};
        margin: 1.1em 0 0.25em 0;
      }
      .scouting-markdown p {
        color: ${colors.textSecondary};
        line-height: 1.6;
        margin: 0.7em 0;
      }
      .scouting-markdown strong {
        color: ${colors.playerA};
        font-weight: 600;
      }
      .scouting-markdown ul,
      .scouting-markdown ol {
        margin: 0.6em 0 0.6em 1.3em;
        color: ${colors.textSecondary};
      }
      .scouting-markdown li {
        margin: 0.3em 0;
        line-height: 1.55;
      }
    `}</style>
  );
}
